# House Price Prediction Project

This project predicts house prices using Machine Learning techniques in Python.

# Import Libraries

In [86]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Load Dataset

In [87]:
df = pd.read_csv("../dataset/housing_data.csv")

# Display Dataset

In [88]:
df.head()

,Id,Area,Bedrooms,Bathrooms,Floors,YearBuilt,Location,Condition,Garage,Price
0,1,1360,5,4,3,1970,Downtown,Excellent,No,149919
1,2,4272,5,4,3,1958,Downtown,Excellent,No,424998
2,3,3592,2,2,3,1938,Downtown,Good,No,266746
3,4,966,4,2,2,1902,Suburban,Fair,Yes,244020
4,5,4926,1,4,2,1975,Downtown,Fair,Yes,636056

# Dataset Shape

In [89]:
df.shape

(2000, 10)

# Dataset Information

In [90]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 10 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Id         2000 non-null   int64
 1   Area       2000 non-null   int64
 2   Bedrooms   2000 non-null   int64
 3   Bathrooms  2000 non-null   int64
 4   Floors     2000 non-null   int64
 5   YearBuilt  2000 non-null   int64
 6   Location   2000 non-null   str
 7   Condition  2000 non-null   str
 8   Garage     2000 non-null   str
 9   Price      2000 non-null   int64
dtypes: int64(7), str(3)
memory usage: 156.4 KB

# Statistical Summary

In [91]:
df.describe()

,Id,Area,Bedrooms,Bathrooms,Floors,YearBuilt,Price
count,2000.000000,2000.000000,2000.000000,2000.00000,2000.000000,2000.000000,2000.000000
mean,1000.500000,2786.209500,3.003500,2.55250,1.993500,1961.446000,537676.855000
std,577.494589,1295.146799,1.424606,1.10899,0.809188,35.926695,276428.845719
min,1.000000,501.000000,1.000000,1.00000,1.000000,1900.000000,50005.000000
25%,500.750000,1653.000000,2.000000,2.00000,1.000000,1930.000000,300098.000000
50%,1000.500000,2833.000000,3.000000,3.00000,2.000000,1961.000000,539254.000000
75%,1500.250000,3887.500000,4.000000,4.00000,3.000000,1993.000000,780086.000000
max,2000.000000,4999.000000,5.000000,4.00000,3.000000,2023.000000,999656.000000

# Check Missing Values

In [92]:
df.isnull().sum()

Id           0
Area         0
Bedrooms     0
Bathrooms    0
Floors       0
YearBuilt    0
Location     0
Condition    0
Garage       0
Price        0
dtype: int64

# Explore Categorical Features

In [93]:
print(df["Location"].unique())
print(df["Condition"].unique())
print(df["Garage"].unique())

<StringArray>
['Downtown', 'Suburban', 'Urban', 'Rural']
Length: 4, dtype: str
<StringArray>
['Excellent', 'Good', 'Fair', 'Poor']
Length: 4, dtype: str
<StringArray>
['No', 'Yes']
Length: 2, dtype: str

# Encode Categorical Variables

In [94]:
df = pd.get_dummies(df, drop_first=True)

# Encoded Dataset Preview

In [95]:
df.head()

,Id,Area,Bedrooms,Bathrooms,Floors,YearBuilt,Price,Location_Rural,Location_Suburban,Location_Urban,Condition_Fair,Condition_Good,Condition_Poor,Garage_Yes
0,1,1360,5,4,3,1970,149919,False,False,False,False,False,False,False
1,2,4272,5,4,3,1958,424998,False,False,False,False,False,False,False
2,3,3592,2,2,3,1938,266746,False,False,False,False,True,False,False
3,4,966,4,2,2,1902,244020,False,True,False,True,False,False,True
4,5,4926,1,4,2,1975,636056,False,False,False,True,False,False,True

# Feature Selection

In [96]:
X = df.drop("Price", axis=1)
y = df["Price"]

# Split Dataset into Training and Testing Sets

In [97]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Train Linear Regression Model

In [98]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()

model.fit(X_train, y_train)

LinearRegression()

# Make Predictions

In [99]:
predictions = model.predict(X_test)

# Evaluate Model Performance

In [100]:
from sklearn.metrics import mean_absolute_error, r2_score

mae = mean_absolute_error(y_test, predictions)
r2 = r2_score(y_test, predictions)

print("MAE:", mae)
print("R2 Score:", r2)

MAE: 242867.44926338628
R2 Score: -0.006181784611834162

# Save Trained Model

In [101]:
import pickle

pickle.dump(model, open("../models/house_price_model.pkl", "wb"))

# Train Random Forest Regressor

In [102]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, r2_score

rf_model = RandomForestRegressor(random_state=42)

rf_model.fit(X_train, y_train)

rf_predictions = rf_model.predict(X_test)

print("MAE:", mean_absolute_error(y_test, rf_predictions))
print("R2 Score:", r2_score(y_test, rf_predictions))

MAE: 249685.404225
R2 Score: -0.07037835002606019

# Sample Checker

In [103]:
sample_data = [[
    1,      # Id
    2500,   # Area
    3,      # Bedrooms
    2,      # Bathrooms
    2,      # Floors
    2005,   # YearBuilt
    0,      # Location_Rural
    1,      # Location_Suburban
    0,      # Location_Urban
    0,      # Condition_Fair
    1,      # Condition_Good
    0,      # Condition_Poor
    1       # Garage_Yes
]]

prediction = model.predict(sample_data)

print("Predicted House Price:", prediction[0])

Predicted House Price: 553502.8855660486

c:\Users\Sai Varun\OneDrive\Desktop\House Price Prediction Project\venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

# Convert Boolean Values to Integers

In [104]:
df = df.astype(int)

# Conclusion

The machine learning models were trained and evaluated successfully for house price prediction. The trained model was also saved for future use.